#!/bin/bash -v
# might be nice at some point to upgrade this to:
# http://stackoverflow.com/a/3090460/450917
# http://pythonpaste.org/scripttest/

pyflakes *.py apt
sudo python setup.py install


apt search gnome-about

apt policy gnome-about

apt install foo bar

apt rm foo

apt cl

apt status less

#~ apt fingerprint

apt searchfiles /bin/less

apt instdeb dude.deb

apt who `which echo`
