#!/bin/bash -v
# might be nice at some point to upgrade this to:
# http://stackoverflow.com/a/3090460/450917
# http://pythonpaste.org/scripttest/

pyflakes *.py apt
sudo python setup.py install


apt search gnome-about -d

apt policy gnome-about -d

apt install foo bar -d

apt rm foo -d

apt cl -d

apt status less -d

#~ apt fingerprint -d

apt searchfiles /bin/less -d

apt instdeb dude.deb -d

